version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "20:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: next
    versions:
    - 10.0.7
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 4.16.1
  - dependency-name: "@types/node"
    versions:
    - 14.14.22
    - 14.14.31
  - dependency-name: eslint
    versions:
    - 7.21.0
  - dependency-name: "@types/react"
    versions:
    - 17.0.2
  - dependency-name: "@types/react-dom"
    versions:
    - 17.0.1
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.16.1
  - dependency-name: typescript
    versions:
    - 4.2.2
  - dependency-name: husky
    versions:
    - 5.1.2
