name: Deploy Github Pages

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Setup Node.js
        uses: actions/setup-node@v2.1.4
        with:
          node-version: '14'
      # TODO: cache
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Build next.js
        run: yarn build
      - name: Export next.js
        run: yarn export
      # for access _next directory
      - name: Add nojekyll
        run: touch ./out/.nojekyll
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
